// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: chatgpt

#ifndef _CHATGPT_UI_COMP_HOOK_H
#define _CHATGPT_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Arc2_create_hook( lv_obj_t *comp );
void ui_comp_Panel2_create_hook( lv_obj_t *comp );
void ui_comp_run_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
