// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: chatgpt

#include "ui.h"

void i2s_adc(lv_event_t * e)
{
	// Your code here
}
