// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: chatgpt

#ifndef _CHATGPT_UI_COMP_H
#define _CHATGPT_UI_COMP_H

#ifdef __cplusplus
extern "C" {
#endif


lv_obj_t * ui_comp_get_child(lv_obj_t *comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;

// COMPONENT Arc2
#define UI_COMP_ARC2_ARC2 0
#define _UI_COMP_ARC2_NUM 1
lv_obj_t *ui_Arc2_create(lv_obj_t *comp_parent);

// COMPONENT Panel2
#define UI_COMP_PANEL2_PANEL2 0
#define _UI_COMP_PANEL2_NUM 1
lv_obj_t *ui_Panel2_create(lv_obj_t *comp_parent);

// COMPONENT run
#define UI_COMP_RUN_RUN 0
#define _UI_COMP_RUN_NUM 1
lv_obj_t *ui_run_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
