// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: chatgpt

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void i2s_adc(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
